export const PRODUCTS = {
  window: {name:'Алюминиевые окна',short:'Окна',rate:19000,labor:2,tech:null},
  sliding: {name:'Раздвижные системы',short:'Раздвижки',rate:31000,labor:3,tech:'sliding'},
  facade: {name:'Светопрозрачные фасады',short:'Фасады',rate:27000,labor:3.5,tech:'facade'}
};
export const FACILITIES = [
  {name:'Небольшая мастерская',area:120,cap:18,workers:3,cost:0},
  {name:'Производственный цех',area:300,cap:36,workers:6,cost:320000},
  {name:'Фасадное производство',area:800,cap:72,workers:12,cost:1200000},
  {name:'Промышленная компания',area:2000,cap:144,workers:24,cost:2800000}
];
export const TECHS = [
  {id:'thermal',name:'Тёплый алюминий',cost:80000,days:3,desc:'Термопрофиль и энергоэффективное остекление. Первый шаг к раздвижным системам.',requires:[]},
  {id:'sliding',name:'Подъёмно-раздвижные системы',cost:120000,days:4,desc:'Новая продукция с ценой 31 000 ₽ за м². Для частных домов и террас.',requires:['thermal']},
  {id:'cnc',name:'Обрабатывающий центр ЧПУ',cost:350000,days:5,desc:'+40% к производительности, +4 к качеству и −10% расхода профиля.',requires:[],facility:1},
  {id:'facade',name:'Стоечно-ригельные фасады',cost:240000,days:5,desc:'Открывает коммерческие фасадные проекты. Требуется инженер и цех 300 м².',requires:['thermal'],facility:1,engineer:true},
  {id:'bim',name:'BIM-проектирование',cost:180000,days:4,desc:'Открывает архитектурные тендеры и сокращает трудоёмкость фасадов на 20%.',requires:['facade'],engineer:true},
  {id:'iso',name:'Контроль качества',cost:100000,days:3,desc:'+6 к качеству. Снижает стоимость гарантийных переделок.',requires:[]}
];
export const ROLES = {
  worker:{name:'Сборщик конструкций',plural:'Сборщики',salary:2100,hire:12000,desc:'+6 рабочих часов в день. Раскрой и сборка конструкций.'},
  installer:{name:'Монтажник',plural:'Монтажники',salary:2000,hire:10000,desc:'Монтаж за 1 день вместо 2. Стоимость монтажа −60%.'},
  engineer:{name:'Инженер-конструктор',plural:'Инженеры',salary:2800,hire:18000,desc:'+3 к качеству. Открывает фасадные технологии и архитектурные проекты.'},
  manager:{name:'Менеджер по продажам',plural:'Менеджеры',salary:1900,hire:10000,desc:'Дополнительная заявка каждые 3 дня и +1 к репутации при сдаче.'}
};
export const STOCK = {profile:{name:'Алюминиевый профиль',unit:'пог. м',price:900,pack:100},glass:{name:'Стеклопакеты',unit:'м²',price:2800,pack:20},fittings:{name:'Комплекты фурнитуры',unit:'компл.',price:1700,pack:10}};
const clients=['Анна Ковалева','Студия «Контур»','Дмитрий Волков','ООО «Новый дом»','Бюро «Форма»','Ирина Соколова','Девелопер «Горизонт»','Алексей Морозов'];
const names={window:['Остекление загородного дома','Окна для городской квартиры','Остекление небольшого офиса','Окна для нового коттеджа'],sliding:['Панорамные двери на террасу','Раздвижки для зимнего сада','Порталы для загородной виллы'],facade:['Входная группа бизнес-центра','Фасад торговой галереи','Остекление общественного здания']};
export function freshState(){return {version:1,day:1,cash:480000,rep:24,brand:8,facility:0,people:{worker:2,installer:0,engineer:0,manager:0},tech:[],research:null,stock:{profile:120,glass:24,fittings:12},deliveries:[],orders:[],offers:[],done:[],transactions:[],logs:[],history:[{day:1,cash:480000,revenue:0}],revenue:0,expenses:0,debt:0,seed:731,serial:1,priceIndex:1,training:0,campaignUntil:0,bankrupt:false,won:false};}
function random(s){s.seed=(s.seed*1664525+1013904223)>>>0;return s.seed/4294967296;}
export function capacity(s){return Math.min(FACILITIES[s.facility].cap,s.people.worker*6)*(s.tech.includes('cnc')?1.4:1)*(1+s.training*.05);}
export function quality(s){return Math.min(99,82+s.people.engineer*3+(s.tech.includes('cnc')?4:0)+(s.tech.includes('iso')?6:0)+s.training*2);}
export function overhead(s){return 2200+FACILITIES[s.facility].area*8+Object.entries(s.people).reduce((t,[r,n])=>t+ROLES[r].salary*n,0);}
export function requirements(s,o){const multiplier=o.type==='sliding'?1.15:o.type==='facade'?1.2:1;return {profile:Math.ceil(o.area*6*multiplier*(s.tech.includes('cnc')?.9:1)),glass:o.area,fittings:Math.ceil(o.area/2*multiplier)};}
export function labor(s,o){return o.area*PRODUCTS[o.type].labor*(o.type==='facade'&&s.tech.includes('bim')?.8:1);}
export function materialCost(s,o){return Object.entries(requirements(s,o)).reduce((t,[k,n])=>t+n*STOCK[k].price*s.priceIndex,0);}
export function log(s,text,tone='info'){s.logs.unshift({day:s.day,text,tone});s.logs=s.logs.slice(0,60);}
function money(s,amount,label,category){s.cash=Math.round(s.cash+amount);if(amount<0)s.expenses+=-amount;s.transactions.unshift({day:s.day,amount:Math.round(amount),label,category});s.transactions=s.transactions.slice(0,250);}
export function addOffer(s,forced){const types=['window'];if(s.tech.includes('sliding'))types.push('sliding');if(s.tech.includes('facade'))types.push('facade');const type=forced||types[Math.floor(random(s)*types.length)];const architect=type==='facade'&&s.tech.includes('bim')&&s.rep>=50;const area=type==='window'?[6,8,10,12,16][Math.floor(random(s)*5)]:type==='sliding'?[8,12,16,20][Math.floor(random(s)*4)]:architect?[50,70,90][Math.floor(random(s)*3)]:[20,28,36][Math.floor(random(s)*3)];const o={id:'ord-'+s.serial++,type,area,client:clients[Math.floor(random(s)*clients.length)],title:names[type][Math.floor(random(s)*names[type].length)],price:Math.round(area*PRODUCTS[type].rate*(1+s.brand*.001)),deadline:s.day+(type==='window'?10:type==='sliding'?13:20),expires:s.day+7,minQuality:architect?90:type==='facade'?85:78,architect,negotiated:false,progress:0,status:'offer'};s.offers.push(o);s.offers=s.offers.slice(-9);return o;}
export function initialState(){const s=freshState();addOffer(s,'window');addOffer(s,'window');addOffer(s,'window');log(s,'Мастерская открыта. Выберите первый заказ — клиент внесёт аванс 50%.','good');return s;}
export function canResearch(s,t){if(s.research)return 'Сначала завершите текущее внедрение';if(t.requires.some(k=>!s.tech.includes(k)))return 'Нужна технология: '+t.requires.filter(k=>!s.tech.includes(k)).map(k=>TECHS.find(t=>t.id===k).name).join(', ');if(t.facility&&s.facility<t.facility)return 'Нужен производственный цех 300 м²';if(t.engineer&&!s.people.engineer)return 'Наймите инженера-конструктора';if(s.cash<t.cost)return 'Недостаточно средств';return null;}
export function expansionRequirements(s){if(s.facility===0)return [{label:'Сдать 5 заказов',value:s.done.length,target:5},{label:'Репутация 30',value:s.rep,target:30}];if(s.facility===1)return [{label:'Сдать 15 заказов',value:s.done.length,target:15},{label:'Репутация 50',value:s.rep,target:50},{label:'Внедрить ЧПУ',value:s.tech.includes('cnc')?1:0,target:1}];return [{label:'Сдать 32 заказа',value:s.done.length,target:32},{label:'Репутация 72',value:s.rep,target:72},{label:'Сдать 5 фасадных проектов',value:s.done.filter(o=>o.type==='facade').length,target:5},{label:'Внедрить BIM',value:s.tech.includes('bim')?1:0,target:1}];}
export function act(s,action,payload={}){
  if(s.bankrupt)throw new Error('Компания обанкротилась. Начните новую игру.');
  if(action==='accept'){const o=s.offers.find(o=>o.id===payload.id);if(!o)throw new Error('Заявка больше недоступна');if(s.orders.length>=3+s.facility*2)throw new Error('Очередь заполнена. Сначала сдайте текущие заказы.');if(quality(s)<o.minQuality)throw new Error('Недостаточное качество: требуется '+o.minQuality);if(o.architect&&!s.people.engineer)throw new Error('Для архитектурного проекта нужен инженер');s.offers=s.offers.filter(x=>x!==o);o.status=o.architect?'design':'queued';if(o.architect)o.designDay=s.day+2;s.orders.push(o);money(s,o.price*.5,'Аванс: '+o.title,'income');log(s,'Принят заказ «'+o.title+'». Получен аванс 50%.','good');}
  else if(action==='negotiate'){const o=s.offers.find(o=>o.id===payload.id);if(!o||o.negotiated)throw new Error('Эти условия уже обсуждались');if(payload.mode==='time'){o.price=Math.round(o.price*.95);o.deadline+=4;log(s,'Клиент согласовал ещё 4 дня в обмен на скидку 5%.');}else if(payload.mode==='price'){if(s.rep<35)throw new Error('Для премиальной цены нужна репутация 35');o.price=Math.round(o.price*1.08);o.deadline-=2;log(s,'Цена согласована на 8% выше. Срок сокращён на 2 дня.');}else throw new Error('Неизвестные условия');o.negotiated=true;}
  else if(action==='buy'){const k=payload.material;if(!STOCK[k])throw new Error('Неизвестный материал');const n=Number(payload.packs);if(!Number.isInteger(n)||n<1||n>10)throw new Error('Выберите от 1 до 10 упаковок');const qty=n*STOCK[k].pack;const cost=Math.round(qty*STOCK[k].price*s.priceIndex);if(s.cash<cost)throw new Error('Недостаточно средств для закупки');money(s,-cost,'Закупка: '+STOCK[k].name,'materials');s.deliveries.push({material:k,qty,day:s.day+2});log(s,'Заказан материал «'+STOCK[k].name+'»: '+qty+'. Поставка через 2 дня.');}
  else if(action==='hire'){const r=payload.role;if(!ROLES[r])throw new Error('Неизвестная должность');if(r==='worker'&&s.people.worker>=FACILITIES[s.facility].workers)throw new Error('В цехе нет места. Расширьте производство.');if(r!=='worker'&&s.people[r]>=2)throw new Error('Штат этой специальности укомплектован');if(s.cash<ROLES[r].hire)throw new Error('Недостаточно средств');money(s,-ROLES[r].hire,'Найм: '+ROLES[r].name,'staff');s.people[r]++;log(s,'В команду принят '+ROLES[r].name.toLowerCase()+'.','good');}
  else if(action==='fire'){const r=payload.role;if(!ROLES[r]||!s.people[r])throw new Error('Нет сотрудников этой должности');if(r==='worker'&&s.people.worker<=1)throw new Error('В производстве должен остаться хотя бы один сборщик');if(r==='engineer'&&s.people[r]===1&&(s.research&&TECHS.find(t=>t.id===s.research.id).engineer||s.orders.some(o=>o.architect)))throw new Error('Инженер занят внедрением или архитектурным проектом');const cost=ROLES[r].salary*7;if(s.cash<cost)throw new Error('Недостаточно средств для компенсации');money(s,-cost,'Компенсация при увольнении','staff');s.people[r]--;log(s,'Штат сокращён: '+ROLES[r].name.toLowerCase()+'.');}
  else if(action==='research'){const t=TECHS.find(t=>t.id===payload.id);if(!t||s.tech.includes(t.id))throw new Error('Технология уже доступна или не существует');const reason=canResearch(s,t);if(reason)throw new Error(reason);money(s,-t.cost,'Внедрение: '+t.name,'investment');s.research={id:t.id,finish:s.day+t.days};log(s,'Начато внедрение: '+t.name+'.');}
  else if(action==='expand'){if(s.facility>=3)throw new Error('Достигнут максимальный масштаб');if(expansionRequirements(s).some(r=>r.value<r.target))throw new Error('Сначала выполните условия расширения');const f=FACILITIES[s.facility+1];if(s.cash<f.cost)throw new Error('Недостаточно средств для расширения');money(s,-f.cost,'Расширение до '+f.area+' м²','investment');s.facility++;log(s,'Открыт новый этап: '+f.name+'.','good');if(s.facility===3){s.won=true;log(s,'Вы построили промышленную компанию! Продолжайте развивать бизнес в свободном режиме.','good');}}
  else if(action==='campaign'){if(s.campaignUntil>s.day)throw new Error('Кампания уже идёт');if(s.cash<35000)throw new Error('Недостаточно средств');money(s,-35000,'Рекламная кампания','brand');s.brand=Math.min(100,s.brand+8);s.campaignUntil=s.day+7;addOffer(s);log(s,'Запущена реклама на 7 дней. Бренд +8, заявки каждый день.','good');}
  else if(action==='portfolio'){if(s.done.length<3)throw new Error('Для портфолио нужны 3 сданных заказа');if(s.cash<20000)throw new Error('Недостаточно средств');money(s,-20000,'Публикация кейса','brand');s.brand=Math.min(100,s.brand+5);s.rep=Math.min(100,s.rep+2);log(s,'Опубликован кейс: бренд +5, репутация +2.','good');}
  else if(action==='training'){if(s.training>=3)throw new Error('Все уровни обучения пройдены');const c=25000*(s.training+1);if(s.cash<c)throw new Error('Недостаточно средств');money(s,-c,'Обучение команды','staff');s.training++;log(s,'Команда прошла обучение: качество +2, производительность +5%.','good');}
  else if(action==='loan'){if(s.debt||s.rep<10)throw new Error('Кредит уже открыт или репутация слишком низкая');money(s,200000,'Кредит: 18% годовых','loan');s.debt=200000;log(s,'Получен кредит 200 000 ₽. Проценты начисляются ежедневно.');}
  else if(action==='repay'){if(!s.debt)throw new Error('Нет открытого кредита');if(s.cash<s.debt)throw new Error('Недостаточно средств для погашения');money(s,-s.debt,'Погашение кредита','loan');s.debt=0;log(s,'Кредит полностью погашен.','good');}
  else if(action==='priority'){const i=s.orders.findIndex(o=>o.id===payload.id);if(i<0)throw new Error('Заказ не найден');const o=s.orders[i];s.orders.splice(i,1);s.orders.unshift(o);log(s,'Заказ «'+o.title+'» поставлен первым в очереди.');}
  else if(action==='nextDay')advance(s);
  else throw new Error('Неизвестное действие');
  return s;
}
function advance(s){s.day++;money(s,-overhead(s),'Аренда, зарплаты и обслуживание','overhead');if(s.debt)money(s,-Math.ceil(s.debt*.18/365),'Проценты по кредиту','interest');
  if(s.day%7===0){s.priceIndex=Number((.95+random(s)*.13).toFixed(2));log(s,'Поставщик обновил прайс. Индекс цен: '+Math.round(s.priceIndex*100)+'%.');}
  const deliveries=s.deliveries.filter(d=>d.day<=s.day);for(const d of deliveries){s.stock[d.material]+=d.qty;log(s,'На склад поступило: '+STOCK[d.material].name+' — '+d.qty+'.','good');}s.deliveries=s.deliveries.filter(d=>d.day>s.day);
  if(s.research&&s.research.finish<=s.day){const id=s.research.id;s.tech.push(id);s.research=null;log(s,'Внедрение завершено: '+TECHS.find(t=>t.id===id).name+'.','good');if(id==='sliding'||id==='facade')addOffer(s,id);}
  let hours=capacity(s);for(const o of s.orders){if(o.status==='design'&&o.designDay<=s.day)o.status='queued';if(o.status==='queued'){const req=requirements(s,o);if(Object.entries(req).some(([k,n])=>s.stock[k]<n))continue;for(const [k,n]of Object.entries(req))s.stock[k]-=n;o.status='production';o.requiredHours=labor(s,o);o.materialsCost=Object.entries(req).reduce((sum,[k,n])=>sum+n*STOCK[k].price*s.priceIndex,0);log(s,'В работе: '+o.title+'.');}if(o.status==='production'&&hours>0){const used=Math.min(hours,o.requiredHours-o.progress);o.progress+=used;hours-=used;if(o.progress>=o.requiredHours)o.status='ready';}if(o.status==='ready'){const cost=Math.round(o.area*(s.people.installer?600:1500));if(s.cash>=cost){money(s,-cost,'Монтаж: '+o.title,'installation');o.status='installation';const installDays=Math.max(s.people.installer?1:2,Math.ceil(o.area/(s.people.installer?s.people.installer*8:12)));const available=s.people.installer?Math.max(s.day,...s.orders.filter(x=>x!==o&&x.status==='installation'&&x.internalInstallation).map(x=>x.deliverDay)):s.day;o.internalInstallation=!!s.people.installer;o.deliverDay=available+installDays;log(s,'Конструкции готовы. Назначен монтаж: '+o.title+'.');}}}
  const complete=s.orders.filter(o=>o.status==='installation'&&o.deliverDay<=s.day);for(const o of complete){const late=Math.max(0,s.day-o.deadline);const penalty=Math.round(Math.min(.2,late*.01)*o.price);const tax=Math.round(o.price*.06);const defect=quality(s)<o.minQuality?Math.round(o.price*.05):0;money(s,o.price*.5,'Окончательный расчёт: '+o.title,'income');money(s,-tax,'УСН 6%: '+o.title,'tax');if(penalty)money(s,-penalty,'Неустойка: '+o.title,'penalty');if(defect)money(s,-defect,'Гарантийная переделка','warranty');s.revenue+=o.price;s.rep=Math.max(0,Math.min(100,s.rep+(late?-3:2)+(s.people.manager?1:0)-(defect?2:0)));s.brand=Math.min(100,s.brand+1);o.status='done';o.completed=s.day;o.penalty=penalty;s.done.unshift(o);log(s,'Сдан заказ «'+o.title+'». '+(late?'Просрочка '+late+' дн.':'В срок.')+' Оплата получена.',late?'warn':'good');}s.orders=s.orders.filter(o=>o.status!=='done');
  s.offers=s.offers.filter(o=>o.expires>=s.day);if(s.day%2===0||s.campaignUntil>s.day)addOffer(s);if(s.people.manager&&s.day%3===0)addOffer(s);
  if(s.cash<-120000){s.bankrupt=true;log(s,'Долг превысил 120 000 ₽. Компания обанкротилась.','warn');}else if(s.cash<overhead(s)*3)log(s,'Денег меньше чем на 3 дня расходов. Проверьте финансы.','warn');
  s.history.push({day:s.day,cash:s.cash,revenue:s.revenue});s.history=s.history.slice(-60);
}
